In [1]:
dist = [20,10,30,40,100,50,30]
speed = [2,3,10,5,8,10,3]

In [4]:
type(dist)

list

In [2]:
dist/speed

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [12]:
!pip install numpy

In [3]:
import numpy as np 

In [5]:
dist = np.array(dist)
speed = np.array(speed)

In [6]:
type(dist)

numpy.ndarray

In [7]:
dist.shape

(7,)

In [11]:
dist//speed

array([10,  3,  3,  8, 12,  5, 10], dtype=int32)

## Pandas

In [13]:
!pip install pandas

In [15]:
import pandas as pd 

In [16]:
# series - 1D
# Dataframe - 2D
# plane - 3D


In [18]:
a = pd.Series([1,2,3])
print(type(a))

<class 'pandas.core.series.Series'>


In [24]:
dist = pd.Series([20,10,30,40,100,50,30,60])
speed = pd.Series([2,3,10,5,8,10,3,6])
time = dist//speed

In [25]:
print(type(time))

<class 'pandas.core.series.Series'>


In [26]:
time

0    10
1     3
2     3
3     8
4    12
5     5
6    10
7    10
dtype: int64

In [28]:
np.array([20,10,30,40,100,50,30,60]).reshape(2,4)

array([[ 20,  10,  30,  40],
       [100,  50,  30,  60]])

In [32]:
b = pd.DataFrame(np.array([20,10,30,40,100,50,30,60,"ABC","PQR"]).reshape(2,5))

In [33]:
b

0   1   2    3    4
0  20  10  30   40  100
1  50  30  60  ABC  PQR

In [34]:
c = pd.Series(["A",10,20,30.15,"PQR"])

In [35]:
c

0        A
1       10
2       20
3    30.15
4      PQR
dtype: object

In [37]:
c = pd.Series(("A",10,20,30.15,"PQR"))

In [38]:
c 

0        A
1       10
2       20
3    30.15
4      PQR
dtype: object

In [42]:
data = np.array([20,10,30,40,100,50,30,60,"ABC","PQR"]).reshape(2,5)
b = pd.DataFrame(data,columns=["Dist","time","age","milage","cost"])
b

Dist time age milage cost
0   20   10  30     40  100
1   50   30  60    ABC  PQR

In [44]:
data = np.array([20,10,30,40,100,50,30,60,"ABC","PQR"]).reshape(2,5)
col = ["Dist","time","age","milage","cost"]
b = pd.DataFrame(data,columns=col,index=["a","b"])
b

Dist time age milage cost
a   20   10  30     40  100
b   50   30  60    ABC  PQR

In [46]:
pd.Timestamp("20221012")

Timestamp('2022-10-12 00:00:00')

In [55]:
df = pd.DataFrame(
            {
                "A":1.0,
                "B":pd.Timestamp("20221012"),
                "C":5,
                "D":"test"
                
            },index=[0]
)

In [56]:
df 

A          B  C     D
0  1.0 2022-10-12  5  test

In [57]:
list(range(4))

[0, 1, 2, 3]

In [60]:
list(range(10,50,10))

[10, 20, 30, 40]

In [61]:
pd.Series(list(range(10,50,10)),index=(list(range(4))),dtype="float32")

0    10.0
1    20.0
2    30.0
3    40.0
dtype: float32

In [1]:
[4,1,2]*4

[4, 1, 2, 4, 1, 2, 4, 1, 2, 4, 1, 2]

In [64]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [65]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
list("ABCD")

['A', 'B', 'C', 'D']

In [76]:
pd.Series(list(range(10,50,10)),index=list("ABCD"),dtype="float32")

A    10.0
B    20.0
C    30.0
D    40.0
dtype: float32

In [101]:
pd.Series(list("ABCD"),index=list([3,2,1,0]),dtype="int32")

ValueError: invalid literal for int() with base 10: 'A'

In [139]:
df = pd.DataFrame(
            {
                "A":1.0,
                "B":pd.Timestamp("20221012"),
                "C":pd.Series(list(range(10,50,10)),index=list([3,2,1,0]),dtype="float32"),
                "D":np.array([3]*4,dtype="int32"),
                "E":pd.Categorical(["red","green","blue","yellow"]),
                "F":"Amit",
                "G":pd.Series(np.arange(4))
                
            }
)

In [89]:
df

A          B     C  D       E     F  G
0  1.0 2022-10-12  40.0  3     red  Amit  0
1  1.0 2022-10-12  30.0  3   green  Amit  1
2  1.0 2022-10-12  20.0  3    blue  Amit  2
3  1.0 2022-10-12  10.0  3  yellow  Amit  3

In [90]:
df.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
G             int32
dtype: object

In [92]:
df.head(2)

A          B     C  D      E     F  G
0  1.0 2022-10-12  40.0  3    red  Amit  0
1  1.0 2022-10-12  30.0  3  green  Amit  1

In [93]:
df.tail(2)

A          B     C  D       E     F  G
2  1.0 2022-10-12  20.0  3    blue  Amit  2
3  1.0 2022-10-12  10.0  3  yellow  Amit  3

In [94]:
df.columns

Index(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='object')

In [95]:
df.index

Int64Index([0, 1, 2, 3], dtype='int64')

In [96]:
df.to_numpy()

array([[1.0, Timestamp('2022-10-12 00:00:00'), 40.0, 3, 'red', 'Amit', 0],
       [1.0, Timestamp('2022-10-12 00:00:00'), 30.0, 3, 'green', 'Amit',
        1],
       [1.0, Timestamp('2022-10-12 00:00:00'), 20.0, 3, 'blue', 'Amit',
        2],
       [1.0, Timestamp('2022-10-12 00:00:00'), 10.0, 3, 'yellow', 'Amit',
        3]], dtype=object)

In [98]:
df.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
G             int32
dtype: object

In [97]:
df.describe()

A          C    D         G
count  4.0   4.000000  4.0  4.000000
mean   1.0  25.000000  3.0  1.500000
std    0.0  12.909945  0.0  1.290994
min    1.0  10.000000  3.0  0.000000
25%    1.0  17.500000  3.0  0.750000
50%    1.0  25.000000  3.0  1.500000
75%    1.0  32.500000  3.0  2.250000
max    1.0  40.000000  3.0  3.000000

In [104]:
df.describe(include='all')

c:\users\amit.kumar02\miniconda3\envs\poc\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Treating datetime data as categorical rather than numeric in `.describe` is deprecated and will be removed in a future version of pandas. Specify `datetime_is_numeric=True` to silence this warning and adopt the future behavior now.
  """Entry point for launching an IPython kernel.


A                    B          C    D       E     F         G
count   4.0                    4   4.000000  4.0       4     4  4.000000
unique  NaN                    1        NaN  NaN       4     1       NaN
top     NaN  2022-10-12 00:00:00        NaN  NaN  yellow  Amit       NaN
freq    NaN                    4        NaN  NaN       1     4       NaN
first   NaN  2022-10-12 00:00:00        NaN  NaN     NaN   NaN       NaN
last    NaN  2022-10-12 00:00:00        NaN  NaN     NaN   NaN       NaN
mean    1.0                  NaN  25.000000  3.0     NaN   NaN  1.500000
std     0.0                  NaN  12.909945  0.0     NaN   NaN  1.290994
min     1.0                  NaN  10.000000  3.0     NaN   NaN  0.000000
25%     1.0                  NaN  17.500000  3.0     NaN   NaN  0.750000
50%     1.0                  NaN  25.000000  3.0     NaN   NaN  1.500000
75%     1.0                  NaN  32.500000  3.0     NaN   NaN  2.250000
max     1.0                  NaN  40.000000  3.0     NaN   NaN  3.000000

In [105]:
df 

A          B     C  D       E     F  G
0  1.0 2022-10-12  40.0  3     red  Amit  0
1  1.0 2022-10-12  30.0  3   green  Amit  1
2  1.0 2022-10-12  20.0  3    blue  Amit  2
3  1.0 2022-10-12  10.0  3  yellow  Amit  3

In [106]:
df.sort_index(axis=0,ascending=False)

A          B     C  D       E     F  G
3  1.0 2022-10-12  10.0  3  yellow  Amit  3
2  1.0 2022-10-12  20.0  3    blue  Amit  2
1  1.0 2022-10-12  30.0  3   green  Amit  1
0  1.0 2022-10-12  40.0  3     red  Amit  0

In [107]:
df.sort_index(axis=1,ascending=False)

G     F       E  D     C          B    A
0  0  Amit     red  3  40.0 2022-10-12  1.0
1  1  Amit   green  3  30.0 2022-10-12  1.0
2  2  Amit    blue  3  20.0 2022-10-12  1.0
3  3  Amit  yellow  3  10.0 2022-10-12  1.0

In [110]:
df.sort_values(by="C",ascending=True)

A          B     C  D       E     F  G
3  1.0 2022-10-12  10.0  3  yellow  Amit  3
2  1.0 2022-10-12  20.0  3    blue  Amit  2
1  1.0 2022-10-12  30.0  3   green  Amit  1
0  1.0 2022-10-12  40.0  3     red  Amit  0

In [112]:
df[1:3]

A          B     C  D      E     F  G
1  1.0 2022-10-12  30.0  3  green  Amit  1
2  1.0 2022-10-12  20.0  3   blue  Amit  2

In [116]:
df.loc[[1,0,3]]

A          B     C  D       E     F  G
1  1.0 2022-10-12  30.0  3   green  Amit  1
0  1.0 2022-10-12  40.0  3     red  Amit  0
3  1.0 2022-10-12  10.0  3  yellow  Amit  3

In [117]:
df.loc[1:3,["C","D"]]

C  D
1  30.0  3
2  20.0  3
3  10.0  3

In [118]:
df.loc[[1,0,3],["C","D"]]

C  D
1  30.0  3
0  40.0  3
3  10.0  3

In [119]:
df.iloc[[1,0,3],[0,2]]

A     C
1  1.0  30.0
0  1.0  40.0
3  1.0  10.0

In [123]:
df.iloc[1:3,2:5]

C  D      E
1  30.0  3  green
2  20.0  3   blue

In [125]:
df.iloc[1:3,2:5]

C  D      E
1  30.0  3  green
2  20.0  3   blue

In [127]:
df

A          B     C  D       E     F  G
0  1.0 2022-10-12  40.0  3     red  Amit  0
1  1.0 2022-10-12  30.0  3   green  Amit  1
2  1.0 2022-10-12  20.0  3    blue  Amit  2
3  1.0 2022-10-12  10.0  3  yellow  Amit  3

In [128]:
df.iloc[1,4]

'green'

In [133]:
df.iat[1,4]

'green'

## Boolean Indexing

In [140]:
df["E"]

0       red
1     green
2      blue
3    yellow
Name: E, dtype: category
Categories (4, object): ['blue', 'green', 'red', 'yellow']

In [143]:
df[df["E"]!="green"]

A          B     C  D       E     F  G
0  1.0 2022-10-12  40.0  3     red  Amit  0
2  1.0 2022-10-12  20.0  3    blue  Amit  2
3  1.0 2022-10-12  10.0  3  yellow  Amit  3

In [146]:
df[df["C"]>20] 

A          B     C  D      E     F  G
0  1.0 2022-10-12  40.0  3    red  Amit  0
1  1.0 2022-10-12  30.0  3  green  Amit  1

In [147]:
np.random.randn?

In [153]:
list("ABCD")

['A', 'B', 'C', 'D']

In [155]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [148]:
df = pd.DataFrame(np.random.randn(6,4),columns=list("ABCD"))
df 

A         B         C         D
0 -1.332898 -1.579978  0.193012  0.135116
1  0.360622  1.771408 -0.188410 -1.044401
2  0.665849 -0.297612  0.114881 -0.762970
3 -0.314829  0.046075 -1.332393  0.289182
4  1.978806 -0.374485  0.646899  2.621115
5 -0.338104  0.170608 -0.807595  0.957449

In [149]:
df["E"] = df["A"]+df["B"]

In [151]:
df["F"]=df["D"]**2

In [152]:
df 

A         B         C         D         E         F
0 -1.332898 -1.579978  0.193012  0.135116 -2.912876  0.018256
1  0.360622  1.771408 -0.188410 -1.044401  2.132030  1.090773
2  0.665849 -0.297612  0.114881 -0.762970  0.368237  0.582124
3 -0.314829  0.046075 -1.332393  0.289182 -0.268754  0.083626
4  1.978806 -0.374485  0.646899  2.621115  1.604321  6.870243
5 -0.338104  0.170608 -0.807595  0.957449 -0.167496  0.916708

In [156]:
df["G"] = list("ABCBCA")

In [157]:
df

A         B         C         D         E         F  G
0 -1.332898 -1.579978  0.193012  0.135116 -2.912876  0.018256  A
1  0.360622  1.771408 -0.188410 -1.044401  2.132030  1.090773  B
2  0.665849 -0.297612  0.114881 -0.762970  0.368237  0.582124  C
3 -0.314829  0.046075 -1.332393  0.289182 -0.268754  0.083626  B
4  1.978806 -0.374485  0.646899  2.621115  1.604321  6.870243  C
5 -0.338104  0.170608 -0.807595  0.957449 -0.167496  0.916708  A

In [160]:
df[df["G"].isin(["A","C"])]

A         B         C         D         E         F  G
0 -1.332898 -1.579978  0.193012  0.135116 -2.912876  0.018256  A
2  0.665849 -0.297612  0.114881 -0.762970  0.368237  0.582124  C
4  1.978806 -0.374485  0.646899  2.621115  1.604321  6.870243  C
5 -0.338104  0.170608 -0.807595  0.957449 -0.167496  0.916708  A

In [161]:
df = pd.DataFrame(np.random.randint(low=1,high=10,size=(6,4)),columns=list("ABCD"))
df 

A  B  C  D
0  3  6  6  9
1  5  2  7  9
2  7  7  1  2
3  3  5  2  9
4  3  4  5  6
5  7  4  2  5

In [162]:
df.mean()

A    4.666667
B    4.666667
C    3.833333
D    6.666667
dtype: float64

In [163]:
df.mean(axis=1)

0    6.00
1    5.75
2    4.25
3    4.75
4    4.50
5    4.50
dtype: float64

## Apply

In [164]:
def my_avg(a):
    return np.mean(a)

In [193]:
df = pd.DataFrame(np.arange(12).reshape(4,3))
df

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [169]:
df.apply(my_avg,axis=1)

0     1.0
1     4.0
2     7.0
3    10.0
dtype: float64

In [170]:
df.mean(axis=1)

0     1.0
1     4.0
2     7.0
3    10.0
dtype: float64

In [180]:
df.apply(lambda x:np.mean(x),axis=1)

0     1.0
1     4.0
2     7.0
3    10.0
dtype: float64

In [177]:
import math
max(1,2,3)

3

## ApplyMap

In [8]:
a = 2 
print(type(a))

<class 'int'>


In [9]:
a*2 

4

In [10]:
b ="2"
print(type(b))

<class 'str'>


In [11]:
b*2

'22'

In [194]:
df

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [195]:
df.dtypes

0    int32
1    int32
2    int32
dtype: object

In [197]:
df = df.astype('str')

In [198]:
df.dtypes

0    object
1    object
2    object
dtype: object

In [204]:
"A"*2

'AA'

In [202]:
def Mytestfn(x):
#     print(type(x))
    return x*2

In [203]:
df.applymap(Mytestfn)

0     1     2
0  00    11    22
1  33    44    55
2  66    77    88
3  99  1010  1111

In [205]:
df.applymap(lambda x:x*2)

0     1     2
0  00    11    22
1  33    44    55
2  66    77    88
3  99  1010  1111

In [2]:
def test(a):
    return a*2 

In [3]:
test(2)

4

In [4]:
g = lambda a:a*2

In [5]:
g(2)

4

In [1]:
import numpy as np 
np.